name: Run test case

on:
    push:
    pull_request:
    release:
        types:
            - published
            - prereleased

jobs:

    run_test_case:

        runs-on: ubuntu-latest
      
        container:
            image: ghcr.io/emqx/emqx-builder/5.3-2:1.15.7-25.3.2-2-ubuntu22.04
      
        steps:
        - uses: actions/checkout@v1
        - name: Run tests
          run: |
            make xref
            make eunit
            make ct
            make cover
        - uses: actions/upload-artifact@v1
          if: always()
          with:
            name: logs
            path: _build/test/logs
        - uses: actions/upload-artifact@v1
          with:
            name: cover
            path: _build/test/cover
